schema = 3

[mod]
  [mod."golang.org/x/mod"]
    version = "v0.36.0"
    hash = "sha256-ZhyOvy9ptbV+pna/CNyQFr5cKRn5O+B2QzkQAISKgco="
  [mod."golang.org/x/sync"]
    version = "v0.20.0"
    hash = "sha256-ybcjhCfK6lroUM0yswUvWooW8MOQZBXyiSqoxG6Uy0Y="
  [mod."golang.org/x/tools"]
    version = "v0.45.0"
    hash = "sha256-fKsYC186cbOCJROZGUqU6UMSxvK2DZ44hlCEytLvp5c="
