# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Main Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  govulncheck:
    uses: asphaltbuffet/.github/.github/workflows/vulncheck.yml@main
  codeql:
    permissions:
      contents: read
      actions: read
      packages: read
      security-events: write
    uses: asphaltbuffet/.github/.github/workflows/codeql.yml@main
  test:
    name: Build and Test
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        run: task ci

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-${{ matrix.os }}
          path: bin

      - name: Upload code coverage results to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./bin/coverage.out
          flags: ${{ runner.os }}

  snapshot:
    needs: test
    name: Release Test
    uses: asphaltbuffet/.github/.github/workflows/release.yml@main
    with:
      snapshot: true