name: Release Workflow

on:
  push:
    # run only against tags
    tags:
      - "v*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  release:
    uses: asphaltbuffet/.github/.github/workflows/release.yml@main
